// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataDBContext))]
    [Migration("20230423190132_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContractDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContractTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContractTotalCost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6442d3ea-986d-4ed0-b249-6993fa75ed83"),
                            ContractDescription = "Разработка ПО для клиента",
                            ContractTitle = "Разработка ПО",
                            ContractTotalCost = "40 млн. руб",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(1315),
                            CustomerId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(1316)
                        },
                        new
                        {
                            Id = new Guid("53b08e3d-7620-4f73-87ee-0b2d2686c179"),
                            ContractDescription = "Обновление ПО для клиента",
                            ContractTitle = "Обновление ПО",
                            ContractTotalCost = "20 млн. руб",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(1323),
                            CustomerId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(1323)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerCompanyTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerCountry")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("CustomerFName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerLName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerMName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerMailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPostAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerTelNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(405),
                            CustomerCompanyTitle = "Экосистемы",
                            CustomerCountry = "Россия",
                            CustomerFName = "Дмитрий",
                            CustomerLName = "Загородский",
                            CustomerMName = "Витальевич",
                            CustomerMailAddress = "EcoSystem@eco.ru",
                            CustomerPostAddress = "г. Москва пр. Ленина 21 офис 14",
                            CustomerTelNumber = "89035678945",
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(410)
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(424),
                            CustomerCompanyTitle = "Энергопроект",
                            CustomerCountry = "Россия",
                            CustomerFName = "Петр",
                            CustomerLName = "Васнецов",
                            CustomerMName = "Петрович",
                            CustomerMailAddress = "energoProject@.ru",
                            CustomerPostAddress = "г. Воронеж ул. Воронина 56 офис 21",
                            CustomerTelNumber = "8910567890",
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(425)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeFName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeJobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmployeeLName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeMName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeMailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeePostAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeTelNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64c2f517-4c27-4e23-adbb-70077bc80834"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4013),
                            EmployeeFName = "Дмитрий",
                            EmployeeJobTitle = "Програмист",
                            EmployeeLName = "Коренков",
                            EmployeeMName = "Васильевич",
                            EmployeeMailAddress = "korenkov@prog.ru",
                            EmployeePostAddress = "г.Москва пр. Маркса 21 ",
                            EmployeeTelNumber = "89056673245",
                            TeamId = new Guid("9e1257c8-00d1-4ba9-80af-f84b8e29431a"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4014)
                        },
                        new
                        {
                            Id = new Guid("d3223d1e-7ccd-4384-ac2c-734634e7b7f3"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4023),
                            EmployeeFName = "Виталий",
                            EmployeeJobTitle = "Аналитик",
                            EmployeeLName = "Валежник",
                            EmployeeMName = "Витальевич",
                            EmployeeMailAddress = "korenkov@prog.ru",
                            EmployeePostAddress = "г.Уфа ул. Ленина 14 ",
                            EmployeeTelNumber = "89076222241",
                            TeamId = new Guid("9e1257c8-00d1-4ba9-80af-f84b8e29431a"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4024)
                        },
                        new
                        {
                            Id = new Guid("ec21ec2e-fc34-4235-9575-066f56c49f5f"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4027),
                            EmployeeFName = "Андрей",
                            EmployeeJobTitle = "Менеджер проекта",
                            EmployeeLName = "Паринков",
                            EmployeeMName = "Витальевич",
                            EmployeeMailAddress = "parinkov@prog.ru",
                            EmployeePostAddress = "г.Мытищи ул. Вологда 33",
                            EmployeeTelNumber = "8970545821",
                            TeamId = new Guid("1c29869d-49e6-4a8e-a1eb-8773497e80fe"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4028)
                        },
                        new
                        {
                            Id = new Guid("33d85a99-bda5-4aca-8904-ece3cb1084ea"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4031),
                            EmployeeFName = "Пётр",
                            EmployeeJobTitle = "Дизайнер",
                            EmployeeLName = "Гордеев",
                            EmployeeMName = "Андреевич",
                            EmployeeMailAddress = "parinkov@prog.ru",
                            EmployeePostAddress = "г.Мытищи ул. Вологда 33",
                            EmployeeTelNumber = "8970545821",
                            TeamId = new Guid("1c29869d-49e6-4a8e-a1eb-8773497e80fe"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(4031)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ProjectFinishData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectTimeSpent")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectTitle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e9c86b9-5976-4713-8c01-1601b74e9d37"),
                            ContractId = new Guid("6442d3ea-986d-4ed0-b249-6993fa75ed83"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2029),
                            ProjectDescription = "Разработка ПО, Разработка и развёртывание",
                            ProjectFinishData = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            ProjectStatus = "InProcess",
                            ProjectTimeSpent = "300 ч",
                            ProjectTitle = "Разработка ПО для компании ECOLine",
                            ProjectType = "Разработка ПО",
                            TeamId = new Guid("9e1257c8-00d1-4ba9-80af-f84b8e29431a"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2031)
                        },
                        new
                        {
                            Id = new Guid("94b1f1ac-30ee-45f8-929a-ad77ca814000"),
                            ContractId = new Guid("53b08e3d-7620-4f73-87ee-0b2d2686c179"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2061),
                            ProjectDescription = "Разработка ПО, Разработка и развёртывание",
                            ProjectFinishData = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ProjectStatus = "InProcess",
                            ProjectTimeSpent = "400 ч",
                            ProjectTitle = "Разработка ПО для компании ТехноМания",
                            ProjectType = "Разработка ПО",
                            TeamId = new Guid("1c29869d-49e6-4a8e-a1eb-8773497e80fe"),
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2062)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TaskDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("TaskFinishData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaskStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("TaskTimeSpent")
                        .HasColumnType("longtext");

                    b.Property<string>("TaskTitle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("278c74e0-bfc0-48c0-8090-ee23cf303dae"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2775),
                            EmployeeId = new Guid("64c2f517-4c27-4e23-adbb-70077bc80834"),
                            ProjectId = new Guid("1e9c86b9-5976-4713-8c01-1601b74e9d37"),
                            TaskDescription = "Моделирование БД для разработки по проекту ECOLine",
                            TaskFinishData = new DateTime(2023, 5, 13, 22, 1, 31, 777, DateTimeKind.Local).AddTicks(2781),
                            TaskStatus = "Stopped",
                            TaskTimeSpent = "12 ч",
                            TaskTitle = "Моделирование БД",
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2777)
                        },
                        new
                        {
                            Id = new Guid("38c87236-80b8-471e-bad4-24c318ba022f"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2787),
                            EmployeeId = new Guid("d3223d1e-7ccd-4384-ac2c-734634e7b7f3"),
                            ProjectId = new Guid("1e9c86b9-5976-4713-8c01-1601b74e9d37"),
                            TaskDescription = "Тестирование ПО по проекту ECOLine",
                            TaskFinishData = new DateTime(2023, 5, 7, 22, 1, 31, 777, DateTimeKind.Local).AddTicks(2790),
                            TaskStatus = "Stopped",
                            TaskTimeSpent = "2 ч",
                            TaskTitle = "Тестирование ПО",
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2788)
                        },
                        new
                        {
                            Id = new Guid("e3e3675a-f500-4f8b-8a44-35a07b540300"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 13, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2794),
                            EmployeeId = new Guid("ec21ec2e-fc34-4235-9575-066f56c49f5f"),
                            ProjectId = new Guid("94b1f1ac-30ee-45f8-929a-ad77ca814000"),
                            TaskDescription = "Разработка UI по проекту ТехноМания",
                            TaskFinishData = new DateTime(2023, 4, 21, 22, 1, 31, 777, DateTimeKind.Local).AddTicks(2796),
                            TaskStatus = "Finished",
                            TaskTimeSpent = "2 ч",
                            TaskTitle = "Разработка UI",
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 21, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(2795)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TeamDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TeamTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e1257c8-00d1-4ba9-80af-f84b8e29431a"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(3426),
                            TeamDescription = "Команда укомлектована аналитиком",
                            TeamTitle = "Команда по проекту EcoLine",
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(3428)
                        },
                        new
                        {
                            Id = new Guid("1c29869d-49e6-4a8e-a1eb-8773497e80fe"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(3432),
                            TeamDescription = "Команда укомлектована дизайнером",
                            TeamTitle = "Команда по проекту ТехноМания",
                            UpdatedBy = "System",
                            UpdatedOn = new DateTime(2023, 4, 23, 19, 1, 31, 777, DateTimeKind.Utc).AddTicks(3432)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f3bd501d-6647-4f51-95ce-412ae3552ed9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "340aa380-03c4-45ab-a8e9-196e2d29f984",
                            Email = "admin@admin",
                            EmailConfirmed = false,
                            FirstName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEKEDcwyDbzgtKJayFDqQtjqdc30H1/pBn4BLjKi4P7GA7MNO0TyymjLTrruZdjEzDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "WCBIVXTPLTZ57TRN53RAKPY6EM6V62CL",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Contract", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Team", "Team")
                        .WithMany("Employees")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.HasOne("Domain.Entities.Contract", "Contract")
                        .WithMany("Projects")
                        .HasForeignKey("ContractId");

                    b.HasOne("Domain.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId");

                    b.Navigation("Contract");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Contract", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
